In [2]:
import pandas as pd

df = pd.read_csv("/Users/camillascandola/Desktop/tn23qv010100.csv")

In [3]:
df.head()

,年次,Year,地域階層,地域コード,地域,District,マーク Mark,面積 Area (km2),千分比 Permillage (‰),Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,令和元,2019.0,0.0,13000.0,東京都,Tokyo-to,NaN,2194.07,-,NaN,NaN,NaN,NaN,NaN,NaN
1,令和2,2020.0,0.0,13000.0,東京都,Tokyo-to,NaN,2194.03,-,NaN,NaN,NaN,NaN,NaN,NaN
2,令和3,2021.0,0.0,13000.0,東京都,Tokyo-to,NaN,2194.05,-,NaN,NaN,NaN,NaN,NaN,NaN
3,令和4,2022.0,0.0,13000.0,東京都,Tokyo-to,NaN,2194.05,-,NaN,NaN,NaN,NaN,NaN,NaN
4,令和5,2023.0,0.0,13000.0,東京都,Tokyo-to,NaN,2199.93,1000,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df["District"].unique()

array(['Tokyo-to', 'All ku', 'Chiyoda-ku', 'Chuo-ku', 'Minato-ku',
       'Shinjuku-ku', 'Bunkyo-ku', 'Taito-ku', 'Sumida-ku', 'Koto-ku',
       'Shinagawa-ku', 'Meguro-ku', 'Ota-ku', 'Setagaya-ku', 'Shibuya-ku',
       'Nakano-ku', 'Suginami-ku', 'Toshima-ku', 'Kita-ku', 'Arakawa-ku',
       'Itabashi-ku', 'Nerima-ku', 'Adachi-ku', 'Katsushika-ku',
       'Edogawa-ku', 'Mouth of Arakawa river',
       'Outer central breakwater landfill site',
       'Shinkaimen landfill site', 'All shi', 'Hachioji-shi',
       'Tachikawa-shi', 'Musashino-shi', 'Mitaka-shi', 'Ome-shi',
       'Fuchu-shi', 'Akishima-shi', 'Chofu-shi', 'Machida-shi',
       'Koganei-shi', 'Kodaira-shi', 'Hino-shi', 'Higashimurayama-shi',
       'Kokubunji-shi', 'Kunitachi-shi', 'Fussa-shi', 'Komae-shi',
       'Higashiyamato-shi', 'Kiyose-shi', 'Higashikurume-shi',
       'Musashimurayama-shi', 'Tama-shi', 'Inagi-shi', 'Hamura-shi',
       'Akiruno-shi', 'Nishitokyo-shi', 'All gun', 'Mizuho-machi',
       'Hinode-machi', 'Hinohara-mura', 'Okutama-machi', 'All islands',
       'Oshima-shicho', 'Oshima-machi', 'Toshima-mura', 'Niijima-mura',
       'Kozushima-mura', 'Miyake-shicho', 'Miyake-mura',
       'Mikurajima-mura', 'Hachijo-shicho', 'Hachijo-machi',
       'Aogashima-mura', 'Others ', 'Ogasawara-shicho', 'Ogasawara-mura',
       nan], dtype=object)

In [11]:
wards = df[df["District"].fillna("").str.endswith("-ku")].copy()

wards["tokyo_ward"] = (wards["District"].str.replace("-ku", "", regex=False))

ward_area = wards[["tokyo_ward", "面積 Area (km2)"]].rename(columns={"面積 Area (km2)": "area_km2"})

ward_area

    tokyo_ward  area_km2
6      Chiyoda     11.66
7         Chuo     10.21
8       Minato     20.36
9     Shinjuku     18.22
10      Bunkyo     11.29
11       Taito     10.11
12      Sumida     13.77
13        Koto     42.99
14   Shinagawa     22.85
15      Meguro     14.67
16         Ota     61.86
17    Setagaya     58.05
18     Shibuya     15.11
19      Nakano     15.59
20    Suginami     34.06
21     Toshima     13.01
22        Kita     20.61
23     Arakawa     10.16
24    Itabashi     32.22
25      Nerima     48.08
26      Adachi     53.25
27  Katsushika     34.80
28     Edogawa     49.90

In [12]:
ward_area.to_csv("ward_area.csv", index=False, encoding="utf-8-sig")